M48
; DRILL file {KiCad 7.0.7} date 2024 July 29, Monday 17:51:52
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-29T17:51:52+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X2.4016Y-2.7953
X2.4016Y-3.2283
X5.1181Y-2.7953
X5.1181Y-3.2283
T0
M30
